name: Deploy to Azure Web App

on:
  push:
    branches: ["azure-deployment"]

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  # Build job
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Build Project
        run: npm run build
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./build

    # Deployment to Azure Web App
  deploy_azure:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          path: ./build

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "word-wind"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BD8257795E7746089CA6B6EB8CFC14AE}}
          package: ./build
